import { Data } from "./types";

export const EXAMPLE_DATA: Data[] = [
  {
    id: "0",
    info: {
      name: "result",
      viewName: "Top Node",
      expression: "a + b",
      unit: "V",
      status: "calc",
      initValue: 0,
      expected: 9,
      dependencies: [],
      dependencyNames: [],
      depth: 0,
      description: "",
      isVisited: false,
    },
  },
  {
    id: "1",
    info: {
      name: "a",
      viewName: "View a",
      expression: "c + d",
      unit: "V",
      status: "calc",
      initValue: 1,
      expected: 7,
      dependencies: [],
      dependencyNames: [],
      depth: 1,
      description: "",
      isVisited: false,
    },
  },
  {
    id: "2",
    info: {
      name: "b",
      viewName: "View b",
      expression: "",
      unit: "V",
      status: "calc",
      initValue: 2,
      expected: 2,
      dependencies: [],
      dependencyNames: [],
      depth: 1,
      description: "",
      isVisited: false,
    },
  },
  {
    id: "3",
    info: {
      name: "c",
      viewName: "View c",
      expression: "",
      unit: "V",
      status: "input",
      initValue: 3,
      expected: 3,
      dependencies: [],
      dependencyNames: [],
      depth: 2,
      description: "",
      isVisited: false,
    },
  },
  {
    id: "4",
    info: {
      name: "d",
      viewName: "View d",
      expression: "",
      unit: "V",
      status: "input",
      initValue: 4,
      expected: 4,
      dependencies: [],
      dependencyNames: [],
      depth: 2,
      description: "",
      isVisited: false,
    },
  },
];

